### PR TITLE
Retrieve avatar {texture} placeholder value via NMS instead of an API

### LINKED ISSUE #975: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```
[ERROR] .... Could not pass event PlayerQuitEvent to DiscordSRV v1.21.2
github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
    at github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1562) ~[?:?]
    at github.scarsz.discordsrv.dependencies.mojang.Mojang.fetch(Mojang.java:81) ~[?:?]
    at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1892) ~[?:?]
    at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1883) ~[?:?]
    at github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1697) ~[?:?]
    at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.PlayerQuitEvent(PlayerJoinLeaveListener.java:132) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-406]
    at org.bukkit.plugin.EventExecutor$$Lambda$3676.0000000014944BD0.execute(Unknown Source) ~[?:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-406]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-406]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:513) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1690) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:502) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:165) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1376) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3147.0000000028186700.run(Unknown Source) ~[?:?]
    at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
    at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
    at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
    at sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:?]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
    at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
    at github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1560) ~[?:?]
... 22 more
```

### LINKED ISSUE #981: DiscordSRV receives 429 errors from Mojang API
When using DiscordSRV, does the console constantly print out the following line whenever a player joins or leaves:
```
[22:38:59 WARN]: Bad response from Mojang API for Andre_601 -> 429 429 - Too Many Requests
```

After systematically removing plugins and checking again was the result that DiscordSRV is printing the above line. This was confirmed by running the server again with all Plugins except DiscordSRV and then with DiscordSRV again, which confirmed this problem.

My guess is, that the API used for retrieving head textures (Crafatar) may have been rate limited by the Mojang API and is probably returning this error now.

### PR DESCRIPTION
**Pull request by Scarsz**
Resolves #975, resolves #981

### CODE REVIEW

File: src/main/java/github/scarsz/discordsrv/DiscordSRV.java [hunk 1]
```diff
@@ -1879,53 +1877,66 @@ public static Message translateMessage(MessageFormat messageFormat, BiFunction<S
...
+    public static String getAvatarUrl(String username, UUID uuid) {
+        String avatarUrl = constructAvatarUrl(username, uuid, "");
+        avatarUrl = PlaceholderUtil.replacePlaceholders(avatarUrl);
+        return avatarUrl;
     }
-    public static String getAvatarUrl(String username) {
-        if (username.startsWith("*")) {
-            // geyser
-            username = username.substring(1);
-        }
```
Comment (Vankka) [inline src/main/java/github/scarsz/discordsrv/DiscordSRV.java:1889]: This might still be useful

File: src/main/java/github/scarsz/discordsrv/DiscordSRV.java [hunk 2]
```diff
@@ -1879,53 +1877,66 @@ public static Message translateMessage(MessageFormat messageFormat, BiFunction<S
...
+        }
+        if (offline && !avatarUrl.contains("{username}")) {
+            if (!offlineUuidAvatarUrlNagged) {
+                DiscordSRV.error("Your AvatarUrl does not contain the {username} placeholder even though this server is using offline UUIDs.");
+                DiscordSRV.error("You should set your AvatarUrl to https://minotar.net/helm/{username}/{size}.png#{texture} to get avatars to work.");
+                offlineUuidAvatarUrlNagged = true;
+            }
         }
 
-        debug("Avatar URL generated: " + avatarUrl);
```
Comment (Vankka) [inline src/main/java/github/scarsz/discordsrv/DiscordSRV.java:1928]: Could still be useful to log this

Comment (Scarsz) [reply src/main/java/github/scarsz/discordsrv/DiscordSRV.java:1928]: Opted not to because of the frequency that they would be shown, I'm down to add it when granular debug options are a thing

Comment (Vankka) [reply src/main/java/github/scarsz/discordsrv/DiscordSRV.java:1928]: Fair point

**Review by Vankka — APPROVED** [review]
