### PR TITLE
Fix custom emotes not being translated in webhook messages

### LINKED ISSUE #1626: DiscordSRV no longer translating certain emojis
### Expected behavior

The plugin should turn emoji codes into their proper emoji

### Actual behavior

Something is causing certain emojis to not translate. I believe it may be the underscores.
Screenshot (660)

### Steps to reproduce

This may be due to the underscore, I am not too sure.

### Server software and version

Paper-309 MC 1.20.2

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by ANutley**
Fixes #1626

### CODE REVIEW

File: src/main/java/github/scarsz/discordsrv/util/WebhookUtil.java [hunk 1]
```diff
@@ -132,6 +132,7 @@ public static void deliverMessage(TextChannel channel, OfflinePlayer player, Str
                     .replace("%username%", player.getName())
                     .replace("%message%", message.replace("[", "\\["));
             chatMessage = PlaceholderUtil.replacePlaceholdersToDiscord(chatMessage, player);
+            chatMessage = DiscordUtil.translateEmotes(message, channel.getGuild());
```
Comment (Dinty1) [inline src/main/java/github/scarsz/discordsrv/util/WebhookUtil.java:135]: Should this not be `chatMessage = DiscordUtil.translateEmotes(chatMessage, channel.getGuild());`?

**Review by Dinty1 — CHANGES_REQUESTED** [review]

**Review by Dinty1 — APPROVED** [review]

**Review by granny — APPROVED** [review]
