### PR TITLE
Linked accounts append-only-file backend

### LINKED ISSUE #1548: Save linked accounts on a timer
### Why?

Linked accounts are currently only saved when the server shuts down correctly, so if the server crashes linked accounts will not be saved.

Some external applications may also be reading the linked_accounts.json file directly for linked accounts

### What and How?

There should be (possibly configurable) timed task for saving linked accounts, they should also not be saved if there haven't been any changes since the last time they were changed.

### Are there alternatives?

No

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by Scarsz**
Closes #1548 

I'll have to look into saving line comments during saving at a later date

### CODE REVIEW

File: src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+        boolean clean = split[split.length - 1].equals("");
+        int modifications = 0;
+        for (String line : split) {
+            Matcher matcher;
+
+            matcher = LINK_PATTERN.matcher(line);
+            if (matcher.matches()) {
+                linkedAccounts.put(
+                        matcher.group("discord"),
+                        UUID.fromString(matcher.group("uuid"))
```
Comment (Vankka) [inline src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java:83]: This might throw if the file is manually edited

File: src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java [hunk 2]
```diff
@@ -0,0 +1,183 @@
...
+                );
+                continue;
+            }
+
+            matcher = MODIFICATION_PATTERN.matcher(line);
+            if (matcher.matches()) {
+                String discord = matcher.group("discord");
+                if (discord != null) linkedAccounts.remove(discord);
+
+                UUID uuid = matcher.group("uuid") != null ? UUID.fromString(matcher.group("uuid")) : null;
```
Comment (Vankka) [inline src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java:93]: This might throw if the file is manually edited

File: src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java [hunk 3]
```diff
@@ -0,0 +1,183 @@
...
+import java.util.UUID;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public class AppendOnlyFileAccountLinkManager extends AbstractFileAccountLinkManager {
+
+    // matches "discordId uuid" with anything after https://regex101.com/r/oRiDUP
+    private static final Pattern LINK_PATTERN = Pattern.compile("^(?<discord>\\d+) (?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}).*");
+    // matches "-discordId" or "-uuid" or "-discord uuid" or "-uuid discord" https://regex101.com/r/SqriBn
+    private static final Pattern MODIFICATION_PATTERN = Pattern.compile("^-(?>(?>(?<discord>\\d+)|(?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})) ?)+$");
```
Comment (Vankka) [inline src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java:46]: The modification pattern doesn't support random crap at the end unlike the link pattern

Comment (Vankka) [reply src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java:46]: This also matches >2 different values separated by spaces

Comment (Vankka) [reply src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java:46]:
```suggestion
    private static final Pattern LINK_PATTERN = Pattern.compile("^(?<discord>\\d+) (?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}).*");
    // matches "-discordId" or "-uuid" or "-discord uuid" or "-uuid discord" https://regex101.com/r/SqriBn
    private static final Pattern MODIFICATION_PATTERN = Pattern.compile("^-(?>(?>(?<discord>\\d+)|(?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})) ?){1,2}.*");
```

File: src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java [hunk 4]
```diff
@@ -0,0 +1,183 @@
...
+            @SuppressWarnings("deprecation") JsonFileAccountLinkManager manager = new JsonFileAccountLinkManager();
+            manager.getLinkedAccounts().forEach(this::link);
+            int count = manager.getLinkedAccountCount();
+
+            File newFile = new File(DiscordSRV.getPlugin().getDataFolder(), "linkedaccounts.json.delete");
+            if (linkedAccountsJsonFile.renameTo(newFile)) {
+                if (!newFile.delete()) newFile.deleteOnExit();
+            } else {
+                if (!linkedAccountsJsonFile.delete()) linkedAccountsJsonFile.deleteOnExit();
+            }
```
Comment (Vankka) [inline src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java:65]: I think the file shouldn't be deleted for now in case the migration doesn't work properly for whatever reason

**Review by Vankka — CHANGES_REQUESTED** [review]
Multiple issues regarding if users go manually editing the file, + this breaks compatibility with things that read the .json file

**Comment by Vankka** [comment]
Would be a good idea to log errors for lines that don't match either of the patterns

**Review by Scarsz — COMMENTED** [review]
> The modification pattern doesn't support random crap at the end unlike the link pattern

I don’t really see that as an issue, the implementation doesn’t add any comments for modification entries because they’ll be deleted later anyway

File: src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java [hunk 5]
```diff
@@ -0,0 +1,183 @@
...
+import java.util.Map;
+import java.util.UUID;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public class AppendOnlyFileAccountLinkManager extends AbstractFileAccountLinkManager {
+
+    // matches "discordId uuid" with anything after https://regex101.com/r/oRiDUP
+    private static final Pattern LINK_PATTERN = Pattern.compile("^(?<discord>\\d+) (?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}).*");
+    // matches "-discordId" or "-uuid" or "-discord uuid" or "-uuid discord" https://regex101.com/r/SqriBn
```
[the remark this answers is not in the document]
Comment (Vankka) [reply src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java:45]:
```suggestion
    // matches "-discordId" or "-uuid" or "-discord uuid" or "-uuid discord" https://regex101.com/r/IkDT4K/
```

**Comment by Scarsz** [comment]
> this breaks compatibility with things that read the .json file

Not a concern for me, I’ve never been a fan of people reading the file manually. It’s clear that the better method to accomplish those tasks is to use JDBC.

> Would be a good idea to log errors for lines that don't match either of the patterns

I didn’t want to clog up the log any more than it already is if something were to break. That should be rare enough for logging the errors to be fine though.

**Comment by Vankka** [comment]
> I didn’t want to clog up the log any more than it already is if something were to break. That should be rare enough for logging the errors to be fine though.

Manual user input, if something is misformatted it will get auto-cleared and the user will just be confused that stuff disappeared

**Comment by Scarsz** [comment]
> > I didn’t want to clog up the log any more than it already is if something were to break. That should be rare enough for logging the errors to be fine though.
> 
> 
> 
> Manual user input, if something is misformatted it will get auto-cleared and the user will just be confused that stuff disappeared

Well, the JSON file would break the entire file if you messed one thing up, lol. Anything’s an improvement over that but I agree we can add a message for it

**Review by Vankka — APPROVED** [review]
